### ISSUE TITLE
tab completion?

### ISSUE THREAD

**Issue by davidguttman** [pavoljuhas/smart-change-directory#1]
First, absolutely love this for zsh. Thank you!

Second, tab completion would be incredible. Any ideas on how I could help make this happen?

**Comment by pavoljuhas** [comment]
Thanks, glad it works for you.  I have implemented some Tab completion in the [scd.vim](https://github.com/pavoljuhas/smart-change-directory/blob/master/vim/plugin/scd.vim) plugin for the Vim editor, where `:Scd <Tab>` completes named directories defined by `scd --alias`.  I feel such completion is not very useful in the shell, because named directories are already completed for `cd ~<Tab>`.  Completion is also not very fitting for a normal scd use, because it is impossible to predict what path pattern does the user want to type.

I feel Tab completion would be useful for completing
- scd options after `scd -<Tab>`
- directories for `scd -a <Tab>`, `scd --unindex <Tab>`, `scd --alias=NAME <Tab>`
- directory names defined in ~/.scdalias.zsh after `scd --unalias <Tab>`.

I don't have much experience with writing zsh completion functions.  If you want to make a crack on it, checking the docs and existing functions such as $fpath/_vim would be a place to start.

**Comment by davidguttman** [comment]
Good points, I'll look into it. 

Didn't know about named directories, that's very useful!
