### ISSUE TITLE
ZSH SCD_HISTORY is messed up OR can't find SCD_SCRIPT

### ISSUE THREAD

**Issue by HeroJeanPierre** [pavoljuhas/smart-change-directory#4]
So this is really weird. Every time I source the zsh file, it iterates between two problem states. The first is this.
 
I'm in home. So I cd'd into my Desktop, and ran. 

`scd -a .`

and this is what appeared in my .scdhistory.

`: 1497752285:0;~/Desktop ~/Desktop ~ ~/Desktop/All_Code/Java ~/Android ~/Desktop/All_Code ~/.scripts/smart-change-directory/bin ~/.scripts/smart-change-directory ~/.scripts
/home/myname/Desktop
: 1497752285:0;~/Desktop ~ ~/Desktop/All_Code/Java ~/Android ~/Desktop/All_Code ~/.scripts/smart-change-directory/bin ~/.scripts/smart-change-directory ~/.scripts`

So I was like what the heck. It's only supposed to add one new directory. So I sourced the file again. And bam, it started putting in directories one at a time: 

`: 1497752128:0;/home/myname/Desktop
: 1497752143:0;/home/myname
: 1497752153:0;/home/myname/Desktop/All_Code/Java
: 1497752157:0;/home/myname`

But when I did 

`scd All`

for example, it would output 

`Warning: running as command with SCD_SCRIPT undefined.`

So that was frustrating. So I restarted my zshrc file again. Low and behold, 

`scd All` 

Sent me to /home/myname/Desktop/All_Code/, however, it was adding directories to the .scdhistory the same way it was in the first problem. 

Any thoughts? Can this be fixed?

**Comment by HeroJeanPierre** [comment]
This is what my .histfile looks like...

`: 1497753843:0;scd --list
: 1497753846:0;cd Downloads
: 1497753918:0;..
: 1497753931:0;e .bash_history
: 1497753943:0;e .zsh_history
: 1497753976:0;e .histfile
: 1497754063:0;subl3 .histfile
: 1497754074:0;cd Android`

**Comment by HeroJeanPierre** [comment]
This problem was fixed when I used the bash_scd instead of the zshell_scd, interesting. Worth looking into.

**Comment by pavoljuhas** [comment]
@HeroJeanPierre - thanks for reporting this - can you try again with zshrc_scd at 8ee2cdebd4c82869f849bbd02a238cb0f976fde0?

The last version should fix the warning on running scd as a command.  This happened because the second pass of zshrc was accidentally un-defining the `scd` function.

As for the strange entries in `.scdhistory` - this could happen _once_ after starting several shell instances at once in different directories as they all attempt to write into the same file, but your HOME directory would need to be on a slower device, for example a network drive.

Another possibility is your shell setup runs some other precmd, preexec or chpwd hook functions (perhaps in a prompt theme) that either do a lot of simultaneous `cd` commands or happen to overwrite the `PWD` shell variable.

Can you check this behavior again with a second terminal window open and running
`tail -f ~/.scdhistory`?

Do the strange entries appear everytime after `scd -a .`?
Do they also appear after just doing some `cd` commands?

**Comment by pavoljuhas** [comment]
Yet another possibility is that some of your shell options are causing unexpected behavior.
Can you replace [line 3 in your bin/scd](https://github.com/pavoljuhas/smart-change-directory/blob/master/bin/scd#L3) with
```
emulate -LR zsh
```
and see if that helps?

Also, can you post the output of `setopt`?  I wonder which zsh option might be causing this.

**Comment by pavoljuhas** [comment]
@HeroJeanPierre - please reopen if there is still a problem.
